@token = {{auth.login.response.body.token}}


### Listar alumnos
GET http://localhost:3000/alumnos
Authorization: Bearer {{token}}
### Crear alumno
POST http://localhost:3000/alumnos
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "nombre": "lukits",
  "apellido": "paz",
  "dni": "14823712"
}

### Obtener alumno por ID
GET http://localhost:3000/alumnos/1
Authorization: Bearer {{token}}
### Actualizar alumno
PUT http://localhost:3000/alumnos/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "nombre": "jose Modificado",
  "apellido": "ruiz",
  "dni": "12321321"
}

### Eliminar alumno
DELETE http://localhost:3000/alumnos/1
Authorization: Bearer {{token}}