@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsInVzZXJFbWFpbCI6Impvc2VAZXhhbXBsZS5jb20iLCJpYXQiOjE3NjI5NzIwODQsImV4cCI6MTc2Mjk4NjQ4NH0.9ifYR5xBia9s1POMPF9hOsymn1WR7OnEGQsp1ozpqXk


### Listar alumnos
GET http://localhost:3000/alumnos
Authorization: Bearer {{token}}
### Crear alumno
POST http://localhost:3000/alumnos
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "nombre": "jotitas",
  "apellido": "Ruiz",
  "dni": "23123123"
}

### Obtener alumno por ID
GET http://localhost:3000/alumnos/2
Authorization: Bearer {{token}}
### Actualizar alumno
PUT http://localhost:3000/alumnos/2
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "nombre": "jose Modificado",
  "apellido": "ruiz",
  "dni": "12321321"
}

### Eliminar alumno
DELETE http://localhost:3000/alumnos/7
Authorization: Bearer {{token}}