
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsInVzZXJFbWFpbCI6Impvc2VAZXhhbXBsZS5jb20iLCJpYXQiOjE3NjI5NzE1MTIsImV4cCI6MTc2Mjk4NTkxMn0.Qc-Z1k1edq5h8byNYj6kpcE4ZYQsUmFlKu8A8cXIy8o



### Listar materias
GET http://localhost:3000/materias
Authorization: Bearer {{token}}

### Crear materia
POST http://localhost:3000/materias
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "nombre": "Laboratorio V",
  "codigo": "LAB5401",
  "anio": 3
}

### Actualizar materia
PUT http://localhost:3000/materias/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "nombre": "Laboratorio Actualizado",
  "codigo": "LAB301",
  "anio": 3
}

### Eliminar materia
DELETE http://localhost:3000/materias/2
Authorization: Bearer {{token}}
